development:
  adapter: postgresql
  encoding: unicode
  database: sin_case_dev
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: sin_case_test
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: sin_case_prod
  pool: 2
  username: your_username
  password: your_password